### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by DarkAndBlue** [aMelonRind/Stereopsis#2]
The following error is getting thrown when starting the game.

latest.log:
```
[13:04:41] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.24
[13:04:41] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[13:04:41] [main/INFO]: Loading 4 mods:
	- fabricloader 0.14.24
	- java 21
	- minecraft 1.20.2
	- stereopsis 1.1.1
[13:04:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/DarkBlue/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:04:41] [main/INFO]: Compatibility level set to JAVA_17
[13:04:44] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 84 milliseconds
[13:04:45] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[13:04:45] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:04:45] [Render thread/INFO]: Setting user: DarkAndBlue
```

From ".minecraft/crash-reports/":
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'stereopsis'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/keybinding/v1/KeyBindingHelper
	at io.github.amelonrind.stereopsis.Stereopsis.onInitializeClient(Stereopsis.java:44)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more
```

I have no other mods installed.
(Also it would be useful to write on modrinth or github if the mod is compatible with sodium or not)

**Comment by DarkAndBlue** [comment]
Adding fabric api to the modlist works. (it starts now)

it would be useful to add fabric api to the dependencies in:
https://github.com/aMelonRind/Stereopsis/blob/master/src/main/resources/fabric.mod.json

**Comment by aMelonRind** [comment]
added
ddeec22
